apiVersion: v1
kind: Secret 
metadata:
  name: backend-secret 
stringData:
  uri: mongodb://mongodb-service:27017
  jwt: abc123
  paypal: AdV8z1VYI9w7sb9-oN4Lp2owyUSJGsFd5rlqjbzoZUs2nEA_XQ_0E5BKXdLP5A_nkt2MsgYyP9a7GE34
